### ISSUE TITLE
Evil Craft Recipes

### ISSUE THREAD

**Issue by BoneDisturbed1** [fyrexgg/SigmaLPCraft#1]
## Bug Report

Recipes for Evil Craft are missing, mostly those that involve Dark Gems

## Expected Behaviour

Recipes for Evil Craft being present?

## Possible Solution

Readd Recipes?

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 0.2.1alpha
* Java Version: v8 update 231
* Launcher Used: Twitch
* Memory Allocated: 10 gigs
* Server/LAN/Single Player: Yes
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by PseudoFyre** [comment]
Fixed. Just forgot to update this.
